# Generated by Django 5.0.6 on 2024-07-05 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonVol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_adulte', models.IntegerField()),
                ('nbre_bebe', models.IntegerField()),
                ('nbre_enfant', models.IntegerField()),
                ('uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_payment', models.CharField(max_length=20)),
                ('uuid', models.UUIDField()),
                ('mon_vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.monvol')),
            ],
        ),
        migrations.AddField(
            model_name='monvol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.user'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.pays')),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('uuid', models.UUIDField()),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateTimeField()),
                ('date_arrivee', models.DateTimeField()),
                ('prix_adulte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_enfant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_bebe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_allee_simple', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_allee_retour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.compagnie')),
                ('ville_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivee', to='flight_app.ville')),
                ('ville_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='flight_app.ville')),
            ],
        ),
        migrations.AddField(
            model_name='monvol',
            name='vol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.vol'),
        ),
    ]
